### ISSUE TITLE
Modify match while accessing its groups.

### ISSUE THREAD

**Issue by Bietola** [ChrisPenner/lens-regex-pcre#13]
I want to be able to do something like this:

``` haskell
solution = "<s-A><s-B><s-C>dksjc<esc>" & [regex|<s-(.*?)>|] . matchWGroups %~ \gs -> gs !! 0
doAssert = solution `shouldBe` "ABCdksjc<esc>"
```

So basically have access to the groups within a match when modifying said match. Is this already possible using other lens operators or might it be a useful feature to add?

**Comment by ChrisPenner** [comment]
The standard `match` combinator stores the groups as the index. Check the last example provided on [match](https://hackage.haskell.org/package/lens-regex-pcre-1.1.0.0/docs/Control-Lens-Regex-ByteString.html#v:match) which uses `%@~`

```haskell
>>> "abc-def, ghi-jkl" & [regex|(\w+)-(\w+)|] . match %@~ \[k, v] _ -> "{" <> k <> ":" <> v <> "}"
"{abc:def}, {ghi:jkl}"
```

I assume that should work for ya?

**Comment by ChrisPenner** [comment]
Closing as I believe this addresses the request, feel free to re-open if needed.

**Comment by Bietola** [comment]
Yes, sorry for the wait. This is exactly what I needed! Thanks.
