### ISSUE TITLE
Broken links in hackage and stackage documentation

### ISSUE THREAD

**Issue by morteako** [ChrisPenner/lens-regex-pcre#5]
First: thank you for an amazing library. It finally made it easy (and fun) to use regex in Haskell.

Issue:
Some links are broken in the documentation at Hackage and Stackage.
F.ex.  the links to the Text and Bytestring tests .
The url for the Text test at Hackage is [http://hackage.haskell.org/package/lens-regex-pcre-1.0.0.0/lens-regex-pcre-1.0.0.0/src./test/Text.hs](http://hackage.haskell.org/package/lens-regex-pcre-1.0.0.0/lens-regex-pcre-1.0.0.0/src./test/Text.hs)
which results in 404.

which I guess should be `lens-regex-pcre-1.0.0.0/src./` instead.
The links are broken at both Hackage and Stackage.

For Hackage only:
The type link urls are wrong.
F.ex. `Int` links to http://hackage.haskell.org/package/lens-regex-pcre-1.0.0.0/base-4.12.0.0/Data-Int.html#t:Int
which results in a 404.

(I don't know anything about how to generate haddock documentation, so I sadly can't help to solve this issue)

**Comment by ChrisPenner** [comment]
Thanks for the heads up; I use relative links in the readme, but I guess those only work on Github. Changed them to absolute, so they should update soonish.

Cheers!
