### ISSUE TITLE
has example typo.

### ISSUE THREAD

**Issue by naoto-ogawa** [ChrisPenner/lens-regex-pcre#8]
The snippet below in the README.md doesn't work. I suppose we don't need dot(.) and match.

```
-- Search
>>> has [regex|whisk|] . match txt
True
```

The snippet below in the blog (https://chrispenner.ca/posts/lens-regex-pcre) does work. 

```
>>> has [regex|wh.skers|] txt
True
```

**Comment by ChrisPenner** [comment]
Thanks! Should be fixed on Github; hackage will update in the next release. 👍
