### ISSUE TITLE
Ignore case and other regex flags?

### ISSUE THREAD

**Issue by mnn** [ChrisPenner/lens-regex-pcre#9]
Is it possible to use `regex` quasiquote with [flags](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp#Parameters)? I didn't find anything related to flags in examples nor tests.

**Comment by ChrisPenner** [comment]
You can either define a custom quasiquoter with your options embedded using `mkRegexTraversalQQ` http://hackage.haskell.org/package/lens-regex-pcre-1.1.0.0/docs/Control-Lens-Regex-ByteString.html#v:mkRegexTraversalQQ

Or you can compile a Regex object using compileM from http://hackage.haskell.org/package/pcre-heavy-1.0.0.2/docs/Text-Regex-PCRE-Heavy.html#v:compileM and pass that to `regexing` http://hackage.haskell.org/package/lens-regex-pcre-1.1.0.0/docs/Control-Lens-Regex-ByteString.html#v:regexing

Hope those help!

**Comment by mnn** [comment]
Thank you for your response, totally missed that in docs. :flushed: 

PS: Anyone using Stack reading this - here are docs for a version currently available in Stack LTS: https://hackage.haskell.org/package/lens-regex-pcre-0.3.1.0/docs/Control-Lens-Regex.html#v:mkRegexQQ
